export const RATING_MAP: Record<string, number> = {
  OBS: 0,
  S1: 1,
  S2: 2,
  S3: 3,
  C1: 4,
  C2: 5,
  C3: 6,
  I1: 7,
  I2: 8,
  I3: 9,
  SUP: 10,
  ADM: 11,
};

export const RANKS = [
  { value: '', label: 'Selecciona tu rango...' },
  { value: 'OBS', label: 'OBS, Piloto/Observador' },
  { value: 'S1', label: 'S1, Controlador de Torre en Prácticas' },
  { value: 'S2', label: 'S2, Controlador de Torre' },
  { value: 'S3', label: 'S3, Controlador de Aproximación' },
  { value: 'C1', label: 'C1, Controlador de Ruta' },
  { value: 'C2', label: 'C2, Controlador Senior' },
  { value: 'C3', label: 'C3, Controlador Senior' },
  { value: 'I1', label: 'I1, Instructor' },
  { value: 'I2', label: 'I2, Instructor Senior' },
  { value: 'I3', label: 'I3, Instructor Senior' },
  { value: 'SUP', label: 'SUP, Supervisor' },
  { value: 'ADM', label: 'ADM, Administrador' },
];
